version: 2.1

jobs:
  commit_lint:
    docker:
      - image: circleci/node:12
    steps:
      - checkout
      - run: mkdir /tmp/tests
      - run: yarn add @commitlint/cli @commitlint/config-conventional commitlint-format-junit
      - run: npx commitlint --from main --to $CIRCLE_BRANCH -o commitlint-format-junit >> /tmp/tests/results.xml
      - store_test_results:
          path: /tmp/tests/  
  build:
    docker:
      - image: circleci/ruby:2.7.1
    steps:
      - checkout
      - run:
          name: install dependencies
          command: |
            bundle install 
      # run tests!
      - run:
          name: run tests
          command: |
            bundle exec rspec 
  publish:
    docker:
      - image: circleci/ruby:2.7.1-node
    steps:
      - checkout
      - run:
          name: install plugins
          command: |            
            git clone git@github.com:angeliski/auto-plugin-gem-canary-release.git ../plugins/auto-plugin-gem-canary-release

      - run:
          name: install dependencies
          command: |
            bundle install 
      - run: gem install gem-release      
      - run:
          name: 'Set github username and email'
          command: |
            git config --global user.email "angeliski@hotmail.com" && \
            git config --global user.name "angeliski"
      - run: |
          curl -vkL -o - https://github.com/intuit/auto/releases/download/v10.22.1/auto-linux.gz | gunzip > ~/auto
          chmod a+x ~/auto

      - run: ~/auto shipit

workflows:
  version: 2
  CI:
    jobs:
      - commit_lint
      - build:
          requires:
            - commit_lint
      - publish:
          requires:
            - build