version: 2.1

jobs:
  commit_lint:
    docker:
      - image: circleci/node:12
    steps:
      - checkout
      - run: mkdir /tmp/tests
      - run: yarn add @commitlint/cli @commitlint/config-conventional commitlint-format-junit
      - run: npx commitlint --from main --to $CIRCLE_BRANCH -o commitlint-format-junit >> /tmp/tests/results.xml
      - store_test_results:
          path: /tmp/tests/  
  build:
    docker:
      - image: circleci/ruby:2.7.1
    steps:
      - checkout
      - run:
          name: install dependencies
          command: |
            bundle install 
      # run tests!
      - run:
          name: run tests
          command: |
            bundle exec rspec 
  publish:
    docker:
      - image: angeliski/auto-ruby-releaser
    steps:
      - checkout
      - run: |
          /auto shipit --verbose


workflows:
  version: 2
  CI:
    jobs:
      - commit_lint
      - build:
          requires:
            - commit_lint
      - publish:
          requires:
            - build